import {ElementPhysicalExcess} from "./element-physical-excess";

let WaterExcesses: string[] = [
    "Acute Arthritis",
    "Bladder disorders",
    'Dark circles around eyes',
    "Dry nose and throat",
    'Edema',
    'Fluid retention',
    'Genital disorders',
    "Headaches",
    "High blood pressure",
    'Hormonal problems',
    "Hypersensitivity to light",
    "Hypersensitive to noise",
    'Infertile',
    'Impotence',
    "Insomnia",
    "Kidney stones",
    "Lacks perspiration",
    "Low back pain",
    "Neurological issues",
    "Prostate issues",
    "Sexual problems",
    "Shallow breathing",
    "Stiff joints",
    'Teeth problems',
    'Urinary Tract infections',
    "Weak gums",
    'Weak knees, legs',
    'Ovarian disorders',
    "Vertigo"
];

export const WaterExcessPhysical: ElementPhysicalExcess = new ElementPhysicalExcess(WaterExcesses);


let WoodExcesses: string[] = [
    'Acid reflux',
    'Addicitons',
    'Arthritis',
    'Auto-immune disorders',
    "Body numbness",
    "Body tingling",
    'Bone aches',
    "Breast Cancer",
    'Bronchitis',
    "Cancer",
    "Cracked nail",
    "Cramps",
    "Cysts",
    "Digestive disturbances",
    "Dizziness",
    'Esophageal issues',
    'Eye disorders',
    'Fatty Liver',
    "Hard nails",
    "Headaches",
    "High blood pressure",
    "Growths",
    "Liver Cancer",
    "Lumps",
    "Migraines",
    "Menstrual problems",
    "Muscle tension",
    'Nervous disorders',
    'Neck & Shoulder pain',
    'Nerve pain',
    "Oily skin, acne",
    "PMS",
    "Sciatica",
    'Sore throats',
    "Spasms",
    'Stiff joints',
    'Stomach issues',
    "Temple pain",
    "Tendon injuries",
    "Tinnitus",
    "Twitching",
    "Visual disturbances",
];

export const WoodExcessPhysical: ElementPhysicalExcess = new ElementPhysicalExcess(WoodExcesses);

let FireExcesses: string[] = [
    "Angina",
    'Buzzing in ears',
    'Bloodshot eyes',
    'Cardiovascular disease',
    'Chest pain',
    'Dizziness',
    "Erratic pulse",
    "Excessive sweating",
    "Fainting spells",
    "Flushed complexion",
    'High Blood pressure',
    "Hives",
    "Hot flashes",
    "Irregular heartbeat",
    'Insomnia',
    'Jittery',
    'Menstrual disorders',
    "Mouth sores",
    'Neck & shoulder pain',
    "Over heat easily",
    'Pain in back, behind Heart',
    "Palpitations",
    "Rashes",
    "Rapid heartbeat",
    "Red, inflamed tongue",
    'Red or white nose',
    'Rushed movements',
    'Shortness of breath',
    "Skin irritations",
    "Sleep disturbances",
    "Speech disturbances",
    'Teeth issues',
    'Uncomfortable in own skin',
    'Varicose veins'
];


export const FireExcessPhysical: ElementPhysicalExcess = new ElementPhysicalExcess(FireExcesses);

let EarthExcesses: string[] = [
    "Abdominal pain",
    "Bowel issues",
    'Constipation',
    'Diarrhea',
    "Edema",
    "Excess appetite",
    "Excess saliva",
    "Fibroid tumours",
    "Frequent bruising",
    "Headaches",
    "Heartburn",
    "Heavy arms & legs",
    "Heavy head",
    "Heavy menstrual flow",
    "Intestinal discomfort",
    "Lack of energy",
    "Metabolic problems",
    "Obesity",
    'Pancreatic disorders',
    "PMS",
    'Sneaks food',
    'Stomach issues',
    'Spleen disorders',
    "Swollen, bleeding gums",
    "Thick mucus",
    "Thyroid issues",
    "Ulcers",
    'Water retention',
    "Weak joints",
    "Weight issues"
];

export const EarthExcessPhysical: ElementPhysicalExcess = new ElementPhysicalExcess(EarthExcesses);


let MetalExcesses: string[] = [
    "Acne",
    "Allergies",
    'Asthma',
    "Awkward movement",
    'Bone marrow disorders',
    'Colds are frequent',
    'Colitis',
    'Dry hair',
    'Dry lips',
    'Dry nails',
    'Dry nasal passages',
    'Dry skin',
    "Eczema",
    'Frequent Flus',
    "Inflexible spine",
    "Intestinal problems",
    "Lack of perspiration",
    'Laryngitis',
    'Mouth disorders',
    "Nasal polyps",
    "Poor circulation",
    "Respiratory problems",
    "Sensitive to weather",
    "Sensitive to smells",
    "Sinus problems",
    "Spine and joint problems",
    "Stiff posture",
    "Stiff and tight muscles",
    'Upper back pain'
];

export const MetalExcessPhysical: ElementPhysicalExcess = new ElementPhysicalExcess(MetalExcesses);
