import {ElementPsychBalance} from "./element-psych-balance";

let WaterPsych: string[] = [
    "Accepts new paths",
    'Calm',
    'Clear',
    "Compassionate",
    'Conserative',
    'Considerate',
    'Consistent',
    "Cool",
    'Creative',
    "Deep thinkers",
    'Determined',
    'Embracing',
    'Encompassing',
    'Enjoys symbolism',
    "Excited about future",
    "Faithful to causes",
    "Fearless, inner drive",
    "Forward moving",
    'Gentle',
    "Has faith in life",
    "Hopeful",
    'Innovative',
    "Insatiably curious",
    "Intellectual",
    "Intelligent",
    "Introspective",
    "Lets the past go",
    'Limitless',
    "Loves the arts",
    'Loves rituals',
    'Loving',
    'Original',
    "Philosophical",
    'Positive',
    'Protective',
    'Prudent',
    "Purposeful",
    "Seeks deep meaning",
    'Sensual',
    'Sensuous',
    'Soft',
    "Spiritual",
    "Stays the course",
    "Steady",
    'Strong willed',
    'Traditional',
    "Visionary",
    "Vivid imaginations",
    "Wise",
];

export const WaterBalancedPsych: ElementPsychBalance = new ElementPsychBalance(WaterPsych);

let WoodPsych: string[] = [
    "Abundant energy",
    "Active",
    'Advocate',
    "Ambitious",
    'Authentic',
    "Bold",
    "Calm under stress",
    "Clear headed",
    "Communicator",
    "Conciliatory",
    "Constructive",
    "Cooperative",
    "Dependable",
    'Confident',
    'Decisive',
    'Determined',
    "Direct",
    "Discreet",
    "Do-er",
    'Ethical',
    'Fair',
    'Fearless',
    'Focused',
    "Forceful",
    "Generous",
    'Genuine',
    "Hard working",
    "Healthy anger",
    "Honest",
    "Humble",
    'Independent',
    "Individualist",
    "Insightful",
    "Inspirational",
    "Intelligent",
    "Kind",
    "Leader",
    'Logical',
    'Loves to debate',
    'Low maintenance',
    'Managerial',
    'Open minded',
    "Overcomes obstacles",
    "Planner",
    "Pleasant",
    "Pioneer",
    "Productive",
    "Progressive",
    'Rational',
    'Reasonable',
    "Relaxed",
    "Solid",
    'Solution oriented',
    'Stable',
    'Strategic',
    'Strong',
    'Sturdy',
    "Team Player",
    'Tenacious',
    'Thoughtful',
    "Truthful",
    'Unapologetic',
    "Visionary",
    "Warrior",
];

export const WoodBalancedPsych: ElementPsychBalance = new ElementPsychBalance(WoodPsych);

let FirePsych: string[] = [
    "Adventurous",
    'Affectionate',
    "Believes in good",
    'Bright',
    'Carefree',
    'Charismatic',
    'Charming',
    'Compassionate',
    "Contagious joy",
    'Demonstrative',
    'Easily inspired',
    "Enthusiastic",
    "Excited about life",
    "Extroverted",
    'Flamboyant',
    'Forgiving',
    "Friendly",
    "Full of energy",
    'Grateful',
    'Happy',
    'Hearty',
    'High energy',
    'High spirited',
    'In the moment',
    "Inspires others",
    "Intense in Love",
    "Intuitive",
    "Joyful",
    'Loving',
    "Loyal",
    'Optimistic',
    "Passionate",
    'Patient',
    'Playful',
    'Polite',
    "Radiant",
    'Refined',
    'Respectful',
    "Seeks excitement",
    "Social",
    "Spiritual",
    'Virtuous',
    "Vivacious",
    "Warm hearted",
    "Wild and bubbly",
    'Wise',
    'Zest for life'
];

export const FireBalancedPsych: ElementPsychBalance = new ElementPsychBalance(FirePsych);

let EarthPsych: string[] = [
    "Accepting",
    'Adaptable',
    'Altruistic',
    'Authentic',
    'Balanced',
    "Caring",
    'Centered',
    "Champion for causes",
    'Clever',
    'Confident',
    'Comfortable',
    "Comforting",
    'Conciliatory',
    'Considerate',
    'Consistent',
    'Convival',
    'Dependable',
    'Elegant',
    'Empathetic',
    "Faithful friend",
    'Fair',
    'Forgiving',
    'Genuine',
    "Good listener",
    "Grounded",
    'Harmonious',
    "Has strong boundaries",
    'Hospitable',
    'In tune',
    "Kind",
    "Loving",
    "Mediator",
    "Non-judgemental",
    'Nurturing',
    'Sociable',
    "Sunny disposition",
    "Sympathetic",
    'Synchronized',
    'On time',
    'Open minded',
    "Patient",
    'Practical',
    'Present',
    'Regular',
    'Reliable',
    'Reasonable',
    'Rooted',
    'Satisfied',
    'Sensible',
    'Sociable',
    'Solid',
    'Spontaneous',
    'Stable',
    "Strives for peace",
    'Supportive',
    'Symphathetic',
    'Synchronized',
    "Tolerant",
    "Trusting",
    'Vigorous',
    "Volunteers",
];

export const EarthBalancedPsych: ElementPsychBalance = new ElementPsychBalance(EarthPsych);



let MetalPsych: string[] = [
    'Affectionate',
    "Alchemist",
    'Aspires to higher causes',
    "Attracted to purity",
    'Austere',
    'Charitable',
    "Conversationalist",
    'Cool',
    'Courageous',
    'Cultivated',
    "Deep thinkers",
    "Devoted to knowledge",
    'Easy going',
    'Elegant',
    'Faithful',
    'Firm',
    'Forgiving',
    'Frank',
    "Future oriented",
    "Great concentration",
    "Has integrity",
    'High values',
    'Honest',
    'Hopeful',
    "High aesthetic sense",
    "High moral standards",
    'Honorable',
    'Humanitarian',
    'In touch',
    "Intellectual",
    "Knowledge seeker",
    "Lets go of past",
    'Loyal',
    'Mature',
    'Pardoning',
    "Patient",
    'Polite',
    "Principled",
    'Proud',
    'Pure',
    'Refined',
    'Resonant',
    'Resolved',
    "Reverent",
    "Seeks excellence",
    "Seeks out beauty",
    'Sensitive',
    'Smooth',
    'Sympathetic',
    'Uplifted',
    "Values quality",
];

export const MetalBalancedPsych: ElementPsychBalance = new ElementPsychBalance(MetalPsych);

