import { ElementPsychExcess} from './element-psych-excess';

let WaterPsych: string[] = [
    'Absent',
    'Agitated',
    "Anti-social",
    "Apathetic",
    'Boring',
    "Can't plan",
    'Cold',
    'Cowardly',
    "Cut off from others",
    "Cynical",
    "Depressed",
    'Destructive',
    "Emotionally unavailable",
    "Equates love with loyalty",
    'Fearful',
    'Fleeting',
    "Hypochondriac",
    'Impulsive',
    "Inability to move forward",
    'Inconsiderate',
    "Inflexible",
    "Insecure",
    "Irritable",
    "Isolates when stressed",
    "Lacks an interest in food",
    'Lewd',
    'Lies',
    "Low interest in others",
    'Negative',
    "Obsessived with sex",
    "Paranoid",
    "Pessimistic",
    "Preoccupation with self",
    'Rough',
    'Scared',
    'Scattered',
    'Slipppery',
    'Small',
    'Stagnant',
    "Suspicious",
    "Tends to withdraw",
    'Terrorized',
    'Timid',
    "Unexplained fears",
    "Unforgiving",
    'Weak'
];

export const WaterExcessPsych: ElementPsychExcess = new ElementPsychExcess(WaterPsych);

let WoodPsych: string[] = [
    "Aggressive",
    "Agitated",
    "Angry at self",
    "Angry at others",
    "Antagonistic",
    "Argumentative",
    'Arrogant',
    "Blames others",
    "Calculating",
    "Competitive",
    "Compulsive",
    "Cunning",
    "Conspicuous",
    "Controlling",
    "Cruel",
    'Dogmatic',
    "Fears being controlled",
    "Fears confinement",
    'Formulistic',
    'Explosive',
    'Hot headed',
    "Hyper vigilant",
    "Inflexible",
    "Insensitive",
    'Insulting',
    "Irritable",
    'Narrow minded',
    'Obscure',
    "Obsessed",
    'Obstinate',
    "Over serious",
    "Questions authority",
    'Rude',
    "Self destructive",
    "Slanderous",
    "Skeptical",
    'Stingy',
    "Suspicious",
    "Traitoristic",
    "Uptight",
    "Vindictive",
    "Violent",
    "Workaholic",
];

export const WoodExcessPsych: ElementPsychExcess = new ElementPsychExcess(WoodPsych);

let FirePsych: string[] = [
    "Agitated energy",
    'Bored easily',
    "Can become delirious",
    "Can\'t concentrate",
    'Cold',
    'Cruel',
    'Cynical',
    'Dispassionate',
    'Dispirited',
    'Dull',
    "Excessive laughing",
    'Exaggerates',
    "Extreme anxiety",
    "Fears inability to project",
    "Feels overwhelmed",
    'Has panic attacks',
    "Has sudden outbursts",
    'Hasty',
    'Hateful',
    'High strung',
    "Hysterical",
    'Impatient',
    "In-attentive",
    "Inappropriate laughter",
    'Inconsiderate',
    'Ill-considered',
    'Ingratiating',
    'Insensitive',
    "Irrational",
    "Lacks appetite",
    'Lacks sense of humor',
    'Melodramatic',
    'Mocking',
    "Mood swings",
    'Nervous',
    'Over commit',
    "Over-eager to please",
    'Obsessed',
    'Obsequious',
    'Panicky',
    'Pretensious',
    "Rapid speech pattern",
    "Restless",
    'Ridicules',
    'Selfish',
    'Shallow',
    'Spiteful',
    'Superstitious',
    'Tackless',
    'Tasteless',
    'Thoughtless',
    'Unfocused',
    'Vicious'
];

export const FireExcessPsych: ElementPsychExcess = new ElementPsychExcess(FirePsych);

let EarthPsych: string[] = [
    'Abusive',
    "Ambivalent",

    'Artificial',
    'Ashamed',
    'Awkward',
    'Biased',
    'Cheater',
    "Compulsive helper",
    "Confused",
    "Difficult with transitions",
    'Dysfunctional',
    'Envious',
    'Fake',
    'Flaky',
    'Gluttonous',
    'Gossipy',
    'Greedy',
    'Guilty',
    "Hypersensitive",
    'Imbalanced',
    'Indecisive',
    'Inconsiderate',
    'Inhospitable',
    'Intrusive',
    'Invasive',
    'Judgemental',
    "Meddlesome",
    "Muddled thinker",
    "Must feel needed",
    'Needy',
    "Obsessive worrier",
    'Out of tune',
    'Over apologizes',
    "Over-involved",
    'Possessive',
    'Prejudice',
    'Selfish',
    'Self Conscious',
    "Self Forsaking",
    'Stubborn',
    'Uncomfortable',
    "Uncompassionate with self",
    'Unfriendly',
    'Unreliable',
    'Unsynchronized',
];

export const EarthExcessPsych: ElementPsychExcess = new ElementPsychExcess(EarthPsych);

let MetalPsych: string[] = [
    'Affected',
    'Avoids feelings',
    "Aloof",
    "Can\'t adapt to change",
    "Can\'t handle conflict",
    "Deceitful",
    "Deceptive",
    "Deeply sad inside",
    "Disciplinarian",
    'Disconnected',
    "Dishonest",
    "Fears losing control",
    "Flat emotionally",
    "Formal",
    "Haughty",
    'Hesitant',
    'Hopeless',
    'Hypercritical',
    'Impolite',
    'Indifferent',
    "Intolerant",
    'Irresponsible',
    "Judgmental",
    'Low self esteem',
    "Mechanical responses",
    'Melancholy',
    "Needs order",
    "Obsessed with cleanliness",
    "Overly critical",
    'Prideless',
    'Reactive',
    "Ritualistic",
    'Rude',
    'Sad',
    "Self Righteous",
    "Strict",
    'Stuck',
    "Stuffy",
    'Tedious',
    "Tends to prejudice opinions",
    'Treacherous',
    "Uncreative",
    "Unoriginal",
    'Unreliable',
];

export const MetalExcessPsych: ElementPsychExcess = new ElementPsychExcess(MetalPsych);
