import {MeridianPhysicalImbalance} from "./meridian-physical-imbalance";

// ----------------------------------STOMACH ------------------------------------------------
let StomachImbalance: string[] = [
    "Acid reflux",
    "Allergies",
    "Always hungry",
    "Anxiety",
    "Bags under Eyes",
    "Bloating",
    "Brain fog",
    "Breast problems",
    "Digestive disorders",
    "Disappointed",
    "Dry lips",
    "Dull skin",
    "Envious",
    "Excessive worry",
    "Facial paralysis",
    "Fallopian Tube Issues",
    "Fears abandonment",
    "Feels disgust",
    "Feels empty",
    "Foot pain",
    "Frequent hunger",
    "Gastric pain",
    "Greedy",
    "Headaches",
    "Jaw Tension",
    "Lacks confidence",
    "Laryngitis",
    "Lumps",
    "Mouth, lip sores",
    "Muscle loss",
    "Neck pains",
    "Nose bleeds",
    "Ovarian issues",
    "People pleaser",
    "Sinus issues",
    "Stuffed nose",
    "Swollen face",
    "Swollen feet",
    "Toothaches",
    "Ulcers",
    "Unaccepting",
    "Unfulfilled",
    "Unhappy",
    "Untrusting",
    "Upper mouth pain",
    "Unsatisfied",
    "Weight issues",
];
export const StomachMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(StomachImbalance);


// ----------------------------------SPLEEN ------------------------------------------------
let SpleenImbalance: string[] = [
    "Abdominal bloating",
    "Aching or painful thighs",
    "Allergies",
    "Anemia",
    "Bad posture",
    "Bleed easily",
    "Bleeding from Anus",
    "Blood disorders",
    "Broken capillaries",
    "Bruise easily",
    "Carpal Tunnel Syndrome",
    "Constipation",
    "Cysts",
    "Diabetes",
    "Diarrhea",
    "Easily tired",
    "Eating disorders",
    "Edema",
    "Excessively worried",
    "Fevers",
    "Fibroids",
    "Gastric pain",
    "Haemorrhoids",
    "Hypoglycemia",
    "Immunodeficiencies",
    "Infections",
    "Lacks appetite",
    "Lethargic",
    "Low body temperature",
    "Low energy",
    "Lumps",
    "Metabolic disorders",
    'Obsessive thoughts',
    "Overly tired",
    "Pale lips",
    "Prolapsed Uterus",
    "Prolapsed Stomach",
    "Prolapsed Bladder",
    "Sore Throats",
    'Swollen abdomen',
    "Swollen lymph",
    "Varicose Veins",
    "Watery, loose stools",
    "Weak muscles",
    "Weight issues",

];
export const SpleenMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(SpleenImbalance);


// -----------------------------------HEART -----------------------------------------------
let HeartImbalance: string[] = [
    "Angina",
    "Armpit pain",
    "Arterial problems",
    "Blood problems",
    "Chest pain",
    "Bleeding gums",
    "Chills easily",
    "Easily over-heated",
    "Circulation problems",
    "Dizziness",
    "High blood pressure",
    "Low blood pressure",
    "Red tongue tip",
    "Insomnia",
    "Aphasia",
    "Heart Palpitations",
    "Swollen Glands",
    "Emotional issues",
    "Feeling disconnected",
    "Stuttering",
    "Confusion",
    "Red face (OE)",
    "Pale face (UE)",
    "Bad dreams",
    'Generalized anxiety',
    'Feelings of panic',
    'Fearful, panicky',
    'Constantly talking',
    'Speaking very fast',
    'Inappropriate laughing',
    "Feeling disconnected",
    'Forgetful',
    'Can not concentrate',
    'Poor memory'
];
export const HeartMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(HeartImbalance);

// -----------------------------------SMALL INTESTINE ----------------------------------------
let SmallIntestineImbalance: string[] = [
    "Abdominal pain",
    "Beer Belly",
    "Ear problems",
    "Deafness",
    "Heart disorders",
    "Knee pain",
    "Bad thigh circulation",
    "Weak thighs",
    "Tinnitus",
    "Pain on biting",
    "Pain with chewing",
    "Weak legs",
    "Indigestion",
    "Bacterial overgrowth",
    "Problem with overeating",
    "Sugar dependencies",
    "Can not make decisions",
    "Afraid of change"
];
export const SmallIntestineMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(SmallIntestineImbalance);


// ----------------------------------BLADDER ------------------------------------------------
let BladderImbalance: string[] = [
    "Ankle problems",
    "Arthritis",
    "Back pain",
    "Bursitis",
    "Calf & Elbow pain",
    "Fallen Arches",
    "Hair loss",
    "Headaches at forehead",
    "Joint pain",
    "Neck tension",
    "Nervous System issues",
    "Osteoporosis",
    "Pigeon toed",
    "Rheumatoid Arthritis",
    "Flat feet",
    "Sciatica",
    "Scoliosis",
    "Tooth loss",
    "UTIs",
    "Varicose Veins",
    "Heart Palpitations",
    "Chest pain",
    "Irritability",
    "Psiatica",
    'Mental confusion',
    "Headaches",
    "Incontinence",
    "Edema",
    "Retention of urine",
    'Stiff neck",' +
    'Lower back pain',
    'Buttock pain',
    "Impatient",
    "Can not relax",
    "Intolerant",
    "Always feels pressured",
    "Hard to cope",
    "Nervous around people",
    "Angry",
    "Uptight",
    "Tense",
    "Stressed out",
    "Unsatisfied perfectionist"
];
export const BladderMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(BladderImbalance);


// ----------------------------------KIDNEYS ------------------------------------------------
let KidneyImbalance: string[] = [
    "Acne",
    "Bone issues",
    "Ear Infections",
    "Edema",
    "Dark circles under eyes",
    "Hardening of the Arteries",
    "Heart Problems",
    "Infertility",
    "Impotence",
    "Knee problems",
    "Adrenal Fatigue",
    "Adrenal Burnout",
    "Low Libido",
    "Lower back problems",
    "Ovarian problems",
    "Sweating feet",
    "Swollen weak ankles",
    "Exhaustion",
    "Immune deficient",
    "Throat problems",
    "Tooth and Gum problems",
    "Low mood or depression",
    "Hard of hearing",
    "Prematurely grey hair",
    "Sore knees",
    "Low libido",
    "Anemia",
    "Backaches",
    "Kidney Stones",
    "Kidney Infections",
    "Fearful of life",
    "Fearful of others",
    "Passive towards others",
    "Bitter",
    "Regretful",
    "Stubborn",
    "Guarded",
    "Stressed out",
    "Weak"

];
export const KidneyMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(KidneyImbalance);

// ----------------------------------PERICARDIUM ------------------------------------------------
let PericardiumImbalance: string[] = [
    "Sore breasts",
    "Carpal Tunnel Syndrome",
    "Hormone problems",
    "Impotence",
    "Nipple pain",
    "Prostate problems",
    "Sacrum problems",
    "Sciatica",
    "Sexual problems",
    "Pericarditis",
    "Sore buttock muscles",
    "Swollen arm pits",
    "Unable to feel joy",
    "Discontented",
    "Lacking joy and fun",
    "Jealous",
    "Resentful",
    "Selfish",
    "Stubborn",
    "Not content",
    "Regretful",
    "Full of remorse",
    "Does not enjoy sex",
    "Blaming self and others",
    "Living in the past",
    "Unforgiving",
    "Lives in the head",
    "Rigid",
    "Inflexible"
];
export const PericardiumMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(PericardiumImbalance);

// ----------------------------------TRIPLE WARMER ------------------------------------------------
let TripleWarmerImbalance: string[] = [
    "Adrenal Exhaustion",
    "Allergies",
    "Asthma",
    "Chills",
    "Diabetes",
    "Emotional Shock",
    "Fever",
    "Hives",
    "Hormonal Issues",
    "Hot Flashes",
    "Hyperthyroid Issues",
    "Hypothyroid Issues",
    "Hypoglycemia",
    "Knee pain or weakness",
    "Menopause issues",
    "Mood swings",
    "Morning fatigue",
    "Over sweating",
    "PMS",
    "Weight problems",
    "Deafness",
    "Wrist pain",
    "Not true to self",
    "Feeling incomplete",
    "No belief in the divine",
    "Constant need to know",
    "Acting fake",
    "Ego driven",
    "Obsessive thoughts",
    "Take on too much",
    "Feel depressed",
    "Try to fix others"

];
export const TripleWarmerMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(TripleWarmerImbalance);


// ----------------------------------GALLBLADDER ------------------------------------------------
let Gallbladderlmbalance: string[] = [
    "Arthritis",
    "Bitter taste in mouth",
    "Gallstones",
    "Grinding teeth, TMJ",
    "High blood pressure",
    "Hip and Knee problems",
    "Jaw pain",
    "Knee pain",
    "Lateral eye pain",
    "Migraine headaches",
    "One sided headaches, ",
    "Sedative abuse",
    "Stimulant abuse",
    "Shingles",
    "Strains",
    "Shoulder pain",
    "Pain on sides of chest",
    "Temple headaches",
    "Insomnia",
    "Diabetes",
    "Feel indecisive",
    "Timid",
    "Easily discouraged",
    "Bitter",
    "Raging",
    "Dislikes people",
    "Ego focused",
    "On edge",
    "Restless",
    "Frustrated with goal attainment",
    "One sided headaches",
    "Feels repressed hatred",
    "Opinionated"
];
export const GallbladderMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(Gallbladderlmbalance);


// -------------------------------------LIVER -----------------------------------------------
let LiverImbalance: string[] = [
    "Blurry vision",
    "Candida",
    "Chest tightness",
    "Eye diseases",
    "Fungus",
    "Hepatitis",
    "Hypertension",
    "Irregular periods",
    "Jaundice",
    "Low sperm count",
    "Menopause issues",
    "Tight chest",
    "Lump in throat",
    "Frequent belching",
    "Dry, cracked nails",
    "Cataracts, floaters",
    "Blurry or dry eyes",
    "Migratory pain",
    "PMS",
    "Thick toenails",
    "Toxicity",
    "Upper back tightness",
    "Headaches",
    "Tinnitus",
    "High Blood Pressure",
    "Frequent headaches",
    "Abdominal distention",
    "Often angry",
    "Easily frustrated",
    "Suffers from depression",
    "Can be a Hypochondriac",
    "Lacks life goals",
    "Often feels stuck",
    "Often irritable",
    "Repressed anger",
    "Yeast infections"
];
export const LiverMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(LiverImbalance);


// ----------------------------------LUNGS ------------------------------------------------
let LungImbalance: string[] = [
    "Bronchitis",
    "Chest congestion",
    "Colds",
    "Congestive heart failure",
    "Coughs",
    "Flu",
    "Insomnia",
    "Respiratory problems",
    "Pleurisy",
    "Pneumonia",
    "Shortness of Breath",
    "Skin problems",
    "Tuberculosis",
    "Chronic lung issues",
    "Unexpressed sadness",
    "Unresolved grief",
    "Can not let go",
    "Hoards possessions",
    "Lives in the past"
];
export const LungMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(LungImbalance);


// ----------------------------------LARGE INTESTINE ------------------------------------------------
let LargeIntestineImbalance: string[] = [
    "Colic",
    "Colon disorders",
    "Constipation",
    "Diarrhea",
    "Gum disease",
    "Hemorrhoids",
    "Herpes, Cold Sores",
    "Hip problems",
    "Low back pain",
    "Mineral deficiencies",
    "Nose problems",
    "Toothaches",
    "Sore throats",
    "Blocked nasal cavity",
    "Diffuse abdomnial pain",
    "Feelings of guilt",
    "Feelings of shame",
    "Feel undervalued",
    "Feel wronged",
    "Low self worth",
    "Diffuse abdominal pain",
    "Feel dirty, unclean",
    "Worries about being judged",
    "Low self esteem",
    "Push loved ones away",
    "Block our feelings",
    "Hide from self evaluation",
    "Feel guilty",
    "Stores childhood trauma"

];
export const LargeIntestineMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(LargeIntestineImbalance);


// ----------------------------------CENTRAL ------------------------------------------------
let CentralImbalance: string[] = [
    "night sweats",
    "anxiety",
    "dizziness",
    "tinnitus",
    "insomnia",
    "infertility",
    "dysmenorrhea",
    "hernia",
    "asthma",
    "sore hips",
    "sore knees",
    "sore ankles",
    "lack of circulation"
];
export const CentralMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(CentralImbalance);


// -----------------------------------GOVERNING --------------------------------------------
let GoverningImbalance: string[] = [
    "back pain",
    "headaches",
    "stiff neck",
    "EPIs",
    "dizziness",
    "tremors",
    "hernia",
    "asthma",
    'poor memory',
    "sore hips",
    "sore knees",
    "sore ankles",
    "lack of circulation"
];
export const GoverningMeridianImbalance: MeridianPhysicalImbalance = new MeridianPhysicalImbalance(GoverningImbalance);
